/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include "../JuceLibraryCode/JuceHeader.h"
#include "MainComponent.h"


class ICubeXMidiWindow : public DocumentWindow
{
public:
    ICubeXMidiWindow() : DocumentWindow ("ICubeX MIDI Test",
                                   Colours::lightgrey,
                                   DocumentWindow::allButtons,
                                         true)
    {
        myMainComponent = new MainWindow();
        setContentOwned(myMainComponent, true);
        centreWithSize(getWidth(), getHeight());
        setVisible(true);
    }
    
    ~ICubeXMidiWindow()
    {
        
    }
    
    void closeButtonPressed() override
    {
        JUCEApplication::quit();
    }
    
    ScopedPointer<MainWindow> myMainComponent;
    

};


//==============================================================================
class NewProjectApplication  : public JUCEApplication
{
public:
    //==============================================================================
    NewProjectApplication() {}

    const String getApplicationName() override       { return ProjectInfo::projectName; }
    const String getApplicationVersion() override    { return ProjectInfo::versionString; }
    bool moreThanOneInstanceAllowed() override       { return true; }

    //==============================================================================
    void initialise (const String& commandLine) override
    {
        // Add your application's initialisation code here..
        myMainWindow = new ICubeXMidiWindow();
        for (int i=0; i<MidiInput::getDevices().size(); i++) {
            myMainWindow->myMainComponent->AddMidiIn(MidiInput::getDevices()[i]);
        }
        for (int i=0; i<MidiOutput::getDevices().size(); i++) {
            myMainWindow->myMainComponent->AddMidiOut(MidiOutput::getDevices()[i]);
        }
        
    }

    void shutdown() override
    {
        // Add your application's shutdown code here..
    }

    //==============================================================================
    void systemRequestedQuit() override
    {
        // This is called when the app is being asked to quit: you can ignore this
        // request and let the app carry on running, or call quit() to allow the app to close.
        quit();
    }

    void anotherInstanceStarted (const String& commandLine) override
    {
        // When another instance of the app is launched while this one is running,
        // this method is invoked, and the commandLine parameter tells you what
        // the other instance's command-line arguments were.
    }
private:
    ScopedPointer<ICubeXMidiWindow> myMainWindow;
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION (NewProjectApplication)
